version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - ai-service
    restart: unless-stopped

  ai-service:
    build: ./ai-service
    ports:
      - "8000:8000"
    restart: unless-stopped
