version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=your_mongodb_uri_here

  ai-service:
    build: ./ai-service
    ports:
      - "8000:8000"
