name: Deploy AI Service

on:
  push:
    paths:
      - "ai-service/**"
      - ".github/workflows/ai.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/unisphere-ai-service:latest ./ai-service
          docker push ${{ secrets.DOCKER_USERNAME }}/unisphere-ai-service:latest

      - name: Trigger Render Deploy
        run: curl -X GET "${{ secrets.RENDER_AI_DEPLOY_HOOK }}"
