name: Deploy Backend

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/unisphere-backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/unisphere-backend:latest

      - name: Trigger Render Deploy
        run: curl -X GET "${{ secrets.RENDER_BACKEND_DEPLOY_HOOK }}"
